#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11,<3.14"
# dependencies = [
#   "deltalake==1.2.1",
#   "pyarrow==21.0.0",
#   "pypdf==6.1.1",
#   "reportlab==4.4.4",
#   "sqlglot==27.28.1",
# ]
# ///
"""Generate and validate the deterministic infrastructure-security reference data.

Mirrors ``generators/finance/generate.py``: four document classes plus ``other``
(vulnerability scan, CVE advisory, pentest report, cloud-posture/compliance
finding) and 3,000 transactional vulnerability-scan findings. A fixed seed makes
every generated byte reproducible. No real company, customer, or system data is
present.

The transactional grain intentionally mirrors Finance's join spine: every
finding carries a ``cve_id``, and the ``cve_advisory`` documents each publish one
``cve_id`` — so ``bronze_scan_findings.cve_id`` joins the extracted
``silver_cve_advisory.cve_id`` exactly the way Finance's ``contract_id`` joins
``agreement_id``. The distinct ``cve_id`` set defines the gold mart grain.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import random
import re
import shutil
import tempfile
from collections import Counter
from collections.abc import Iterable
from datetime import date, datetime, timedelta, timezone
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path
from typing import Any

import pyarrow as pa
import sqlglot
from deltalake import DeltaTable, write_deltalake
from pypdf import PdfReader
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.pdfgen import canvas

SEED = 20260923
ROW_COUNT = 3_000
GENERATED_AT = datetime(2026, 9, 23, 12, 0, tzinfo=timezone.utc)
GENERATED_AT_MS = int(GENERATED_AT.timestamp() * 1_000)
CLASSES = (
    "vulnerability_scan",
    "cve_advisory",
    "pentest_report",
    "cloud_posture_finding",
    "other",
)
ROWS_PER_CLASS = 5
MONEY = Decimal("0.01")
SCORE = Decimal("0.1")

TXN_FIELDS = (
    "finding_id",
    "scan_id",
    "scan_date",
    "detected_timestamp",
    "asset_id",
    "asset_name",
    "asset_type",
    "environment",
    "business_unit",
    "owner_team",
    "cve_id",
    "vulnerability_title",
    "vulnerability_category",
    "severity",
    "cvss_score",
    "cvss_vector",
    "status",
    "first_detected_date",
    "age_days",
    "remediation_hours",
    "asset_value_at_risk",
    "weighted_risk",
    "remediation_sla_days",
    "exploit_available",
    "detection_source",
    "source_updated_at",
)

# (asset_id, name, type, environment, business_unit, owner_team, criticality, base_value, weight)
ASSETS = (
    ("AST-001", "core-payments-api", "Server", "Production", "Payments Platform", "Platform SRE", "Critical", Decimal("2400000.00"), 13),
    ("AST-002", "auth-identity-svc", "Container", "Production", "Identity & Access", "IAM Engineering", "Critical", Decimal("1950000.00"), 12),
    ("AST-003", "customer-portal-web", "Server", "Production", "Digital Experience", "Web Platform", "High", Decimal("1200000.00"), 10),
    ("AST-004", "orders-postgres-prod", "Database", "Production", "Commerce", "Data Platform", "Critical", Decimal("2100000.00"), 12),
    ("AST-005", "analytics-spark-cluster", "Cloud VM", "Production", "Data & Analytics", "Data Platform", "High", Decimal("880000.00"), 8),
    ("AST-006", "edge-waf-gateway", "Network Device", "Production", "Network Security", "Network Security", "Critical", Decimal("1600000.00"), 11),
    ("AST-007", "billing-batch-worker", "Container", "Production", "Payments Platform", "Platform SRE", "High", Decimal("740000.00"), 8),
    ("AST-008", "hr-records-db", "Database", "Production", "People Operations", "Enterprise Apps", "High", Decimal("960000.00"), 9),
    ("AST-009", "internal-wiki", "Server", "Staging", "Corporate IT", "Enterprise Apps", "Medium", Decimal("210000.00"), 4),
    ("AST-010", "ci-build-runner", "Cloud VM", "Development", "Developer Platform", "Developer Platform", "Medium", Decimal("330000.00"), 5),
    ("AST-011", "logging-elastic-node", "Cloud VM", "Production", "Observability", "Platform SRE", "High", Decimal("620000.00"), 7),
    ("AST-012", "vpn-concentrator", "Network Device", "Production", "Network Security", "Network Security", "Critical", Decimal("1300000.00"), 11),
    ("AST-013", "mobile-bff-api", "Container", "Production", "Digital Experience", "Web Platform", "High", Decimal("690000.00"), 8),
    ("AST-014", "data-lake-gateway", "Cloud VM", "Production", "Data & Analytics", "Data Platform", "High", Decimal("980000.00"), 9),
    ("AST-015", "sso-broker", "Container", "Production", "Identity & Access", "IAM Engineering", "Critical", Decimal("1500000.00"), 11),
    ("AST-016", "marketing-cms", "Server", "Staging", "Marketing", "Web Platform", "Low", Decimal("120000.00"), 3),
    ("AST-017", "reporting-warehouse", "Database", "Production", "Finance Systems", "Enterprise Apps", "High", Decimal("1050000.00"), 9),
    ("AST-018", "container-registry", "Cloud VM", "Production", "Developer Platform", "Developer Platform", "High", Decimal("810000.00"), 8),
    ("AST-019", "secrets-vault", "Container", "Production", "Identity & Access", "IAM Engineering", "Critical", Decimal("2250000.00"), 13),
    ("AST-020", "partner-integration-gw", "Server", "Production", "Partnerships", "Integration Team", "High", Decimal("700000.00"), 7),
    ("AST-021", "dev-sandbox-box", "Cloud VM", "Development", "Developer Platform", "Developer Platform", "Low", Decimal("90000.00"), 2),
    ("AST-022", "backup-orchestrator", "Server", "Production", "Infrastructure", "Platform SRE", "Medium", Decimal("410000.00"), 5),
    ("AST-023", "email-relay", "Server", "Production", "Corporate IT", "Enterprise Apps", "Medium", Decimal("300000.00"), 5),
    ("AST-024", "iot-telemetry-hub", "Network Device", "Staging", "Product Engineering", "Integration Team", "Medium", Decimal("360000.00"), 4),
)

SCANNERS = ("Nessus", "Qualys VMDR", "Wiz", "Rapid7 InsightVM", "CrowdStrike Spotlight")

VULN_CATEGORIES = (
    "Remote Code Execution",
    "Privilege Escalation",
    "SQL Injection",
    "Information Disclosure",
    "Denial of Service",
    "Authentication Bypass",
    "Insecure Deserialization",
    "Path Traversal",
    "Cross-Site Scripting",
    "Cryptographic Weakness",
)

# Base remediation effort (hours) by category — deterministic per finding before
# a small seeded jitter. Higher for the harder-to-fix classes.
CATEGORY_BASE_HOURS = {
    "Remote Code Execution": Decimal("16.0"),
    "Privilege Escalation": Decimal("12.0"),
    "SQL Injection": Decimal("10.0"),
    "Information Disclosure": Decimal("6.0"),
    "Denial of Service": Decimal("8.0"),
    "Authentication Bypass": Decimal("14.0"),
    "Insecure Deserialization": Decimal("13.0"),
    "Path Traversal": Decimal("7.0"),
    "Cross-Site Scripting": Decimal("5.0"),
    "Cryptographic Weakness": Decimal("9.0"),
}

# The five CVEs that ship a cve_advisory PDF. These are the document join keys:
# every one appears in the transactional findings, and each advisory PDF states
# its cve_id prominently so ai_extract lands a clean, unique join value.
# (cve_id, title, category, cvss_score, cvss_vector, severity, exploit_available,
#  affected_products, remediation, references)
DOCUMENTED_CVES = (
    (
        "CVE-2026-31847",
        "Unauthenticated remote code execution in the request-routing filter",
        "Remote Code Execution",
        Decimal("9.8"),
        "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "Critical",
        True,
        "Gateway Filter Framework 4.2.0–4.6.3; Edge Router bundles shipping it",
        (
            "Upgrade the framework to 4.6.4 or apply the vendor hotfix, then restart "
            "every gateway pod and rotate any credentials reachable from the routing "
            "tier. Block the crafted routing header at the WAF as an interim control."
        ),
        ("https://example.test/advisories/GFF-2026-014", "https://example.test/kb/routing-rce"),
    ),
    (
        "CVE-2026-20415",
        "Heap overflow in the TLS session-resumption handler",
        "Denial of Service",
        Decimal("7.5"),
        "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
        "High",
        False,
        "OpenComms TLS library 3.0.0–3.0.9; services statically linking it",
        (
            "Rebuild affected services against 3.0.10, redeploy, and disable "
            "session-resumption tickets on internet-facing listeners until patched."
        ),
        ("https://example.test/advisories/OC-2026-3", "https://example.test/kb/tls-resume-overflow"),
    ),
    (
        "CVE-2025-48291",
        "SQL injection in the reporting parameter binder",
        "SQL Injection",
        Decimal("8.6"),
        "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:L/A:N",
        "High",
        True,
        "Reporting Warehouse Connector 2.1.x prior to 2.1.7",
        (
            "Upgrade the connector to 2.1.7, which parameterizes the report filter, "
            "and review query logs for injection attempts against the reporting "
            "warehouse. Restrict the connector's database role to read-only."
        ),
        ("https://example.test/advisories/RWC-2025-22",),
    ),
    (
        "CVE-2026-10022",
        "Authentication bypass via forged assertion in the SSO broker",
        "Authentication Bypass",
        Decimal("9.1"),
        "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        "Critical",
        True,
        "SSO Broker 5.4.0–5.5.2",
        (
            "Patch to 5.5.3, invalidate all active sessions, and enforce signature "
            "validation on inbound assertions. Audit administrative logins issued "
            "during the exposure window."
        ),
        ("https://example.test/advisories/SSO-2026-1", "https://example.test/kb/assertion-forgery"),
    ),
    (
        "CVE-2025-53914",
        "Sensitive data exposure through verbose error responses",
        "Information Disclosure",
        Decimal("5.3"),
        "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
        "Medium",
        False,
        "Customer Portal Web 8.x prior to 8.3.1",
        (
            "Upgrade to 8.3.1 to suppress stack traces in production responses and "
            "enable the generic error page. Confirm debug mode is disabled in the "
            "production configuration."
        ),
        ("https://example.test/advisories/CPW-2025-9",),
    ),
)

# Product tokens used to synthesize titles for the undocumented CVEs.
_PRODUCT_TOKENS = (
    "the message queue broker",
    "the container runtime shim",
    "the object-storage SDK",
    "the metrics collector agent",
    "the workflow scheduler",
    "the API gateway plugin",
    "the log-shipping daemon",
    "the identity federation module",
    "the caching proxy",
    "the backup client",
    "the service-mesh sidecar",
    "the configuration server",
)


def _severity_for(score: Decimal) -> str:
    """CVSS base score → qualitative severity band (CVSS v3.1 ranges)."""
    if score >= Decimal("9.0"):
        return "Critical"
    if score >= Decimal("7.0"):
        return "High"
    if score >= Decimal("4.0"):
        return "Medium"
    return "Low"


def _sla_for(severity: str) -> int:
    """Remediation SLA (days) by severity — the workshop's fixed policy."""
    return {"Critical": 7, "High": 30, "Medium": 90, "Low": 180}[severity]


def build_cve_catalog() -> dict[str, dict[str, Any]]:
    """The full CVE catalog: the five documented CVEs plus synthesized extras.

    Every finding references a ``cve_id`` from this catalog, so a CVE's category,
    CVSS, severity, and exploit flag are consistent across all its findings (a
    CVSS base score is a per-CVE property, not a per-finding one).
    """
    catalog: dict[str, dict[str, Any]] = {}
    for (
        cve_id,
        title,
        category,
        cvss,
        vector,
        severity,
        exploit,
        _products,
        _remediation,
        _refs,
    ) in DOCUMENTED_CVES:
        catalog[cve_id] = {
            "cve_id": cve_id,
            "title": title,
            "category": category,
            "cvss_score": cvss,
            "cvss_vector": vector,
            "severity": severity,
            "exploit_available": exploit,
            "documented": True,
        }

    rng = random.Random(SEED + 7_000)
    # A spread of CVSS bases so severity bands are all represented.
    cvss_pool = [
        Decimal(value)
        for value in (
            "9.8", "9.1", "8.8", "8.2", "7.5", "7.1", "6.8", "6.5",
            "5.9", "5.3", "4.7", "4.3", "3.7", "3.1",
        )
    ]
    for index in range(45):
        year = 2025 if index % 3 == 0 else 2026
        cve_id = f"CVE-{year}-{40000 + index * 137}"
        category = VULN_CATEGORIES[index % len(VULN_CATEGORIES)]
        cvss = cvss_pool[index % len(cvss_pool)]
        product = _PRODUCT_TOKENS[index % len(_PRODUCT_TOKENS)]
        title = f"{category} in {product}"
        catalog[cve_id] = {
            "cve_id": cve_id,
            "title": title,
            "category": category,
            "cvss_score": cvss,
            "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
            "severity": _severity_for(cvss),
            "exploit_available": rng.random() < 0.3,
            "documented": False,
        }
    return catalog


def weighted_choice(rng: random.Random, values: Iterable[tuple[Any, int]]) -> Any:
    choices = list(values)
    return rng.choices(
        [value for value, _ in choices], weights=[weight for _, weight in choices], k=1
    )[0]


def dollars(value: Decimal) -> str:
    return f"${value:,.2f}"


def wrap(text: str, width: int) -> list[str]:
    words = text.split()
    lines: list[str] = []
    current: list[str] = []
    for word in words:
        if len(" ".join(current + [word])) > width and current:
            lines.append(" ".join(current))
            current = [word]
        else:
            current.append(word)
    if current:
        lines.append(" ".join(current))
    return lines


class SecurityPdf:
    """Deterministic canvas helper with deliberately varied layouts.

    A structural twin of the Finance generator's ``FinancePdf`` (same invariant
    reportlab settings, so bytes are reproducible) with a security-styled header.
    """

    def __init__(self, path: Path, title: str, accent: colors.Color, variant: int):
        path.parent.mkdir(parents=True, exist_ok=True)
        self.pdf = canvas.Canvas(
            str(path),
            pagesize=letter,
            pageCompression=1,
            invariant=1,
            pdfVersion=(1, 4),
        )
        self.title = title
        self.accent = accent
        self.variant = variant
        self.page = 0
        self.pdf.setTitle(title)
        self.pdf.setAuthor("Synthetic Stryker Databricks Workshop")
        self.new_page()

    def new_page(self) -> None:
        if self.page:
            self.footer()
            self.pdf.showPage()
        self.page += 1
        if self.variant % 2:
            self.pdf.setFillColor(self.accent)
            self.pdf.rect(0, 738, 612, 54, fill=1, stroke=0)
            self.pdf.setFillColor(colors.white)
            self.pdf.setFont("Helvetica-Bold", 16)
            self.pdf.drawString(36, 758, self.title[:66])
        else:
            self.pdf.setFillColor(colors.black)
            self.pdf.setFont("Helvetica-Bold", 17)
            self.pdf.drawString(42, 757, self.title[:64])
            self.pdf.setStrokeColor(self.accent)
            self.pdf.setLineWidth(3)
            self.pdf.line(42, 744, 570, 744)
        self.y = 714

    def footer(self) -> None:
        self.pdf.setFillColor(colors.HexColor("#5B6573"))
        self.pdf.setFont("Helvetica", 7)
        self.pdf.drawString(
            40, 24, "Synthetic workshop document — no real company or system data"
        )
        self.pdf.drawRightString(570, 24, f"Page {self.page}")

    def heading(self, text: str) -> None:
        self.pdf.setFillColor(self.accent)
        self.pdf.setFont("Helvetica-Bold", 11)
        self.pdf.drawString(42, self.y, text.upper())
        self.y -= 18

    def text(
        self, text: str, *, size: int = 9, indent: int = 0, leading: int = 12
    ) -> None:
        self.pdf.setFillColor(colors.HexColor("#20252B"))
        self.pdf.setFont("Helvetica", size)
        for line in wrap(text, max(38, int((510 - indent) / (size * 0.52)))):
            if self.y < 54:
                self.new_page()
            self.pdf.drawString(42 + indent, self.y, line)
            self.y -= leading
        self.y -= 3

    def kv(self, pairs: list[tuple[str, str]], columns: int = 2) -> None:
        col_width = 258 if columns == 2 else 172
        row_height = 30
        for start in range(0, len(pairs), columns):
            if self.y < 70:
                self.new_page()
            row = pairs[start : start + columns]
            for col, (label, value) in enumerate(row):
                x = 42 + col * col_width
                self.pdf.setFillColor(colors.HexColor("#667085"))
                self.pdf.setFont("Helvetica-Bold", 7)
                self.pdf.drawString(x, self.y, label.upper())
                self.pdf.setFillColor(colors.black)
                self.pdf.setFont("Helvetica", 9)
                self.pdf.drawString(x, self.y - 13, value[:44])
            self.y -= row_height
        self.y -= 4

    def table(
        self, headers: list[str], rows: list[list[str]], widths: list[int]
    ) -> None:
        font_size = 7
        height = 22
        x0 = 42
        if self.y < 100:
            self.new_page()
        self.pdf.setFillColor(self.accent)
        self.pdf.rect(x0, self.y - 15, sum(widths), 20, fill=1, stroke=0)
        self.pdf.setFillColor(colors.white)
        self.pdf.setFont("Helvetica-Bold", font_size)
        x = x0
        for header, width in zip(headers, widths):
            self.pdf.drawString(x + 3, self.y - 8, header[: int(width / 4.3)])
            x += width
        self.y -= 19
        for row_no, row in enumerate(rows):
            if self.y < 58:
                self.new_page()
            if row_no % 2 == 0:
                self.pdf.setFillColor(colors.HexColor("#F2F4F7"))
                self.pdf.rect(x0, self.y - 16, sum(widths), height, fill=1, stroke=0)
            self.pdf.setFillColor(colors.black)
            self.pdf.setFont("Helvetica", font_size)
            x = x0
            for value, width in zip(row, widths):
                max_chars = max(5, int(width / 4.0))
                display = (
                    value
                    if stringWidth(value, "Helvetica", font_size) < width - 6
                    else value[: max_chars - 1] + "…"
                )
                self.pdf.drawString(x + 3, self.y - 9, display)
                x += width
            self.y -= height
        self.y -= 8

    def finish(self) -> None:
        self.footer()
        self.pdf.save()


def vulnerability_scan_pdf(path: Path, index: int, rng: random.Random) -> dict[str, str]:
    scan_id = f"SCAN-2026-{4200 + index * 13}"
    scan_date = date(2026, 8, 4) + timedelta(days=index * 5)
    scanner = SCANNERS[index % len(SCANNERS)]
    scopes = (
        "Production payments and identity tier",
        "Customer-facing web and mobile edge",
        "Data platform and reporting warehouse",
        "Network security appliances",
        "Developer platform and CI estate",
    )
    titles = (
        "Vulnerability Scan Report",
        "Authenticated Scan Summary",
        "Weekly Exposure Report",
        "External Attack-Surface Scan",
        "Infrastructure Vulnerability Assessment",
    )
    total = 180 + index * 42 + rng.randint(3, 40)
    critical = 6 + index * 2
    high = 24 + index * 5
    medium = 70 + index * 12
    low = total - critical - high - medium
    doc = SecurityPdf(path, titles[index], colors.HexColor("#B42318"), index)
    doc.text(
        f"Scanner {scanner} | Scan {scan_id} | Scope: {scopes[index]}. This report "
        "summarizes detected vulnerabilities across the in-scope assets; it is a "
        "scan summary, not a single-CVE advisory or a manual penetration test."
    )
    doc.kv(
        [
            ("Scan ID", scan_id),
            ("Scan date", scan_date.isoformat()),
            ("Scanner", scanner),
            ("Authenticated", "Yes" if index % 2 else "No"),
            ("Assets in scope", str(18 + index * 3)),
            ("Highest CVSS", "9.8" if index < 3 else "8.6"),
        ]
    )
    doc.heading("Severity summary")
    doc.table(
        ["Severity", "Count", "SLA (days)", "Breaching SLA"],
        [
            ["Critical", str(critical), "7", str(max(0, critical - 2))],
            ["High", str(high), "30", str(max(0, high - 9))],
            ["Medium", str(medium), "90", str(medium // 4)],
            ["Low", str(low), "180", "0"],
        ],
        [150, 95, 110, 103],
    )
    doc.heading("Top findings")
    doc.table(
        ["CVE", "Asset", "Category", "CVSS", "Status"],
        [
            ["CVE-2026-31847", "core-payments-api", "Remote Code Execution", "9.8", "Open"],
            ["CVE-2026-10022", "sso-broker", "Authentication Bypass", "9.1", "In Remediation"],
            ["CVE-2025-48291", "reporting-warehouse", "SQL Injection", "8.6", "Open"],
            ["CVE-2026-20415", "edge-waf-gateway", "Denial of Service", "7.5", "Open"],
        ],
        [110, 150, 130, 45, 73],
    )
    doc.new_page()
    doc.heading("Methodology and coverage")
    doc.text(
        "The scan enumerated network services, performed authenticated checks "
        "where credentials were provided, and correlated detected software "
        "versions against known-vulnerability data. Findings are de-duplicated "
        "per asset and CVE. Counts reflect the state at scan time and supersede "
        "the prior weekly report."
    )
    doc.heading("Remediation guidance")
    doc.text(
        "Prioritize the critical remote-code-execution and authentication-bypass "
        "findings on production payments and identity assets. Apply vendor "
        "patches referenced in the per-CVE advisories, restart affected services, "
        "and re-scan to confirm closure. Track exceptions as accepted risk with an "
        "owner and review date."
    )
    doc.finish()
    return {"document_subtype": titles[index], "document_id": scan_id}


def cve_advisory_pdf(path: Path, index: int, rng: random.Random) -> dict[str, str]:
    (
        cve_id,
        title,
        category,
        cvss,
        vector,
        severity,
        exploit,
        products,
        remediation,
        refs,
    ) = DOCUMENTED_CVES[index]
    published = date(2026, 6, 3) + timedelta(days=index * 11)
    doc = SecurityPdf(path, f"Security Advisory {cve_id}", colors.HexColor("#6941C6"), index)
    doc.text(
        f"{cve_id} — {title}. This advisory describes a single vulnerability, its "
        "affected products, and the recommended remediation. It is the "
        "authoritative per-CVE record that vulnerability-scan findings reference."
    )
    doc.kv(
        [
            ("CVE ID", cve_id),
            ("Published", published.isoformat()),
            ("Last updated", (published + timedelta(days=4)).isoformat()),
            ("Severity", severity),
            ("CVSS v3.1 base", str(cvss)),
            ("Exploit observed", "Yes" if exploit else "No"),
        ]
    )
    doc.heading("CVSS vector")
    doc.text(vector)
    doc.heading("Affected products")
    doc.text(products)
    doc.heading("Description")
    doc.text(
        f"A {category.lower()} weakness allows an attacker to compromise affected "
        "deployments. Successful exploitation impacts the confidentiality, "
        "integrity, or availability of the service depending on configuration. "
        "The condition is present in the versions listed above and is resolved in "
        "the fixed release."
    )
    doc.new_page()
    doc.heading("Recommended remediation")
    doc.text(remediation)
    doc.heading("Detection")
    doc.text(
        f"Vulnerability scanners flag {cve_id} on assets running an affected "
        "version. Confirm the installed version, apply the fix, and re-scan. "
        "Where an immediate patch is not possible, apply the interim mitigation "
        "and record an accepted-risk exception with a review date."
    )
    doc.heading("References")
    doc.table(
        ["#", "Reference"],
        [[str(i + 1), ref] for i, ref in enumerate(refs)],
        [40, 418],
    )
    doc.text(
        "This advisory does not include customer data. Treat the remediation "
        "window as bounded by the severity-based SLA for the affected assets."
    )
    doc.finish()
    return {"document_subtype": f"{severity} advisory", "document_id": cve_id}


def pentest_report_pdf(path: Path, index: int, rng: random.Random) -> dict[str, str]:
    engagement = f"PT-2026-{70 + index * 3}"
    start = date(2026, 5, 6) + timedelta(days=index * 21)
    end = start + timedelta(days=9)
    testers = ("A. Okafor", "R. Mehta", "L. Petrov", "S. Nakamura", "J. Alvarez")
    scopes = (
        "External perimeter and public web applications",
        "Internal network segmentation and lateral movement",
        "Identity provider and single sign-on",
        "Cloud control plane and data services",
        "Payments processing environment",
    )
    risks = ("High", "Critical", "High", "Medium", "Critical")
    titles = (
        "Penetration Test Report",
        "Red-Team Engagement Report",
        "Application Security Assessment",
        "Cloud Penetration Test",
        "Payments Environment Pentest",
    )
    doc = SecurityPdf(path, titles[index], colors.HexColor("#B54708"), index + 1)
    doc.text(
        f"Engagement {engagement} | Tester {testers[index]} | Scope: {scopes[index]}. "
        "This is a manual penetration-test report: it documents exploited attack "
        "paths and prioritized recommendations, not an automated scan summary."
    )
    doc.kv(
        [
            ("Engagement ID", engagement),
            ("Test type", ["Black-box", "Red-team", "Grey-box", "Cloud", "Grey-box"][index]),
            ("Start date", start.isoformat()),
            ("End date", end.isoformat()),
            ("Overall risk", risks[index]),
            ("Findings", str(7 + index * 2)),
        ]
    )
    doc.heading("Exploited attack paths")
    doc.table(
        ["#", "Attack path", "Impact", "Related CVE"],
        [
            ["1", "Forged SSO assertion → admin console", "Critical", "CVE-2026-10022"],
            ["2", "Injected report filter → data read", "High", "CVE-2025-48291"],
            ["3", "Routing header → gateway RCE", "Critical", "CVE-2026-31847"],
        ],
        [30, 235, 90, 103],
    )
    doc.text(
        "Each path was validated in a controlled window with the blue team "
        "notified. No production data was exfiltrated; proof-of-concept access "
        "was demonstrated and then revoked."
    )
    doc.new_page()
    doc.heading("Prioritized recommendations")
    doc.text(
        "1. Enforce signature validation on inbound SSO assertions and rotate "
        "broker signing keys. 2. Parameterize the reporting filter and constrain "
        "the connector's database role. 3. Patch the gateway routing filter and "
        "add a WAF rule for the crafted header. 4. Add detection for anomalous "
        "administrative logins."
    )
    doc.heading("Retest")
    doc.text(
        "A retest is recommended within 30 days of remediation to confirm each "
        "exploited path is closed. Findings map to per-CVE advisories where a CVE "
        "identifier applies; process and configuration findings do not carry a CVE."
    )
    doc.finish()
    return {"document_subtype": titles[index], "document_id": engagement}


def cloud_posture_finding_pdf(path: Path, index: int, rng: random.Random) -> dict[str, str]:
    finding_ref = f"CSPM-{2026}-{5300 + index * 17}"
    detected = date(2026, 7, 9) + timedelta(days=index * 6)
    providers = ("AWS", "Azure", "GCP", "AWS", "Azure")
    services = ("S3", "Storage Account", "Cloud Storage", "IAM", "Key Vault")
    controls = ("CIS 2.1.1", "CIS 3.6", "CIS 5.2", "CIS 1.16", "CIS 8.4")
    benchmarks = (
        "CIS AWS Foundations 3.0",
        "CIS Azure 2.1",
        "CIS GCP 2.0",
        "CIS AWS Foundations 3.0",
        "CIS Azure 2.1",
    )
    severities = ("High", "Medium", "High", "Critical", "Medium")
    titles = (
        "Cloud Posture Finding",
        "Compliance Control Finding",
        "CSPM Misconfiguration Report",
        "Cloud Security Posture Finding",
        "Configuration Compliance Finding",
    )
    doc = SecurityPdf(path, titles[index], colors.HexColor("#067647"), index)
    doc.text(
        f"Finding {finding_ref} | {providers[index]} {services[index]} | Control "
        f"{controls[index]}. This is a cloud-posture / compliance finding raised by "
        "continuous configuration monitoring — a control deviation on a cloud "
        "resource, distinct from a software-CVE advisory."
    )
    doc.kv(
        [
            ("Finding ID", finding_ref),
            ("Cloud provider", providers[index]),
            ("Service", services[index]),
            ("Control", controls[index]),
            ("Benchmark", benchmarks[index]),
            ("Severity", severities[index]),
            ("Region", ["us-east-1", "westeurope", "us-central1", "us-west-2", "eastus"][index]),
            ("Status", ["Open", "Open", "In Remediation", "Open", "Resolved"][index]),
        ]
    )
    doc.heading("Deviation")
    doc.text(
        "The monitored resource does not meet the referenced benchmark control. "
        "The current configuration weakens the resource's security posture and "
        "should be brought into compliance. This finding is configuration-level "
        "and does not reference a software CVE."
    )
    doc.new_page()
    doc.heading("Affected resource")
    doc.table(
        ["Attribute", "Value"],
        [
            ["Resource ID", f"arn:example:{services[index].lower()}:{finding_ref}"],
            ["Account / subscription", f"acct-{4100 + index * 7}"],
            ["Owner team", ["Platform SRE", "Data Platform", "Enterprise Apps", "IAM Engineering", "Web Platform"][index]],
            ["First detected", detected.isoformat()],
        ],
        [150, 308],
    )
    doc.heading("Remediation guidance")
    doc.text(
        "Apply the benchmark-recommended configuration (enable encryption, "
        "restrict public access, or enforce key rotation as applicable), then "
        "confirm the control passes on the next posture evaluation. Track any "
        "exception as accepted risk with an owner and review date."
    )
    doc.finish()
    return {"document_subtype": titles[index], "document_id": finding_ref}


def other_pdf(path: Path, index: int, rng: random.Random) -> dict[str, str]:
    subtypes = (
        "Security Policy Document",
        "Incident Response Runbook",
        "Risk Acceptance Memo",
        "Change Advisory Notice",
        "Security Awareness Bulletin",
    )
    ids = ("POL-SEC-0142", "IRP-2026-08", "RISK-ACC-2026-31", "CHG-2026-6620", "BULL-2026-19")
    title = subtypes[index]
    doc_id = ids[index]
    doc = SecurityPdf(path, title, colors.HexColor("#C11574"), index)
    doc.text(
        "Information Security Program | Supporting security record intentionally "
        "outside the primary four-class taxonomy (scan / advisory / pentest / "
        "cloud-posture). It deliberately mentions CVEs, scans, and remediation so "
        "a classifier must weigh the document's purpose, not isolated keywords."
    )
    doc.kv(
        [
            ("Reference", doc_id),
            ("Document date", (date(2026, 7, 12) + timedelta(days=index * 8)).isoformat()),
            ("Owner", ["CISO Office", "SOC", "Risk & Compliance", "Change Mgmt", "Security Awareness"][index]),
            ("Classification", "Internal"),
        ]
    )
    if index == 0:
        doc.heading("Vulnerability management policy")
        doc.text(
            "This policy sets remediation SLAs by severity (Critical 7 days, High "
            "30, Medium 90, Low 180), defines the exception process, and assigns "
            "asset owners. It governs how scan findings and CVE advisories are "
            "triaged but is not itself a scan or an advisory."
        )
        doc.table(
            ["Severity", "SLA (days)", "Approver"],
            [["Critical", "7", "CISO"], ["High", "30", "Security lead"], ["Medium", "90", "Team lead"]],
            [150, 150, 158],
        )
    elif index == 1:
        doc.heading("Incident response runbook")
        doc.text(
            "Steps for responding to a confirmed exploitation of a known CVE: "
            "isolate the asset, preserve evidence, rotate credentials, apply the "
            "advisory's remediation, and re-scan. Includes on-call escalation and "
            "communication templates."
        )
        doc.table(
            ["Phase", "Action", "Owner"],
            [
                ["Detect", "Confirm the alert and scope", "SOC"],
                ["Contain", "Isolate the affected asset", "Platform SRE"],
                ["Eradicate", "Apply advisory remediation", "Asset owner"],
                ["Recover", "Re-scan and monitor", "SOC"],
            ],
            [110, 240, 108],
        )
    elif index == 2:
        doc.heading("Risk acceptance memo")
        doc.text(
            "Documents a time-bound accepted-risk decision for a medium-severity "
            "finding on a staging asset where the patch requires a maintenance "
            "window. Includes the compensating control and the review date; it is "
            "not a scan or advisory."
        )
        doc.table(
            ["Field", "Value"],
            [
                ["Related finding", "CVE-2025-53914 on internal-wiki"],
                ["Compensating control", "Network restriction to VPN"],
                ["Review date", "2026-10-15"],
                ["Approved by", "Risk & Compliance"],
            ],
            [150, 308],
        )
    elif index == 3:
        doc.heading("Change advisory notice")
        doc.text(
            "Announces a scheduled patching change to remediate critical findings "
            "on production payments assets. Lists the maintenance window, rollback "
            "plan, and the CVEs addressed. It authorizes a change, not a finding."
        )
        doc.table(
            ["Change", "Window", "Addresses"],
            [
                ["Gateway patch", "2026-08-24 02:00Z", "CVE-2026-31847"],
                ["SSO broker patch", "2026-08-25 02:00Z", "CVE-2026-10022"],
            ],
            [150, 150, 158],
        )
    else:
        doc.heading("Security awareness bulletin")
        doc.text(
            "A staff-facing bulletin on recognizing phishing that targets "
            "credentials for internet-facing systems. It references recent "
            "advisories for context but is educational content, not a technical "
            "finding."
        )
        doc.table(
            ["Topic", "Guidance"],
            [
                ["Phishing", "Report suspicious mail to the SOC"],
                ["MFA", "Never approve an unexpected prompt"],
                ["Patching", "Restart when prompted after updates"],
            ],
            [150, 308],
        )
    doc.new_page()
    doc.heading("Review and approval trail")
    doc.text(
        "Prepared for synthetic workshop use. This record is not a vulnerability "
        "scan, a CVE advisory, a penetration-test report, or a cloud-posture "
        "finding; classification should reflect that."
    )
    doc.table(
        ["Role", "Reviewer", "Status", "Date"],
        [
            ["Preparer", ["A. Kim", "J. Ellis", "R. Shah", "M. Costa", "K. Diaz"][index], "Submitted", "2026-08-19"],
            ["Security", "Information security", "Reviewed", "2026-08-20"],
            ["Compliance", "Risk & compliance", "No exception", "2026-08-21"],
        ],
        [95, 170, 105, 88],
    )
    doc.finish()
    return {"document_subtype": title, "document_id": doc_id}


PDF_BUILDERS = {
    "vulnerability_scan": vulnerability_scan_pdf,
    "cve_advisory": cve_advisory_pdf,
    "pentest_report": pentest_report_pdf,
    "cloud_posture_finding": cloud_posture_finding_pdf,
    "other": other_pdf,
}


def generate_pdfs(output_root: Path) -> None:
    documents = output_root / "documents"
    if documents.exists():
        for class_name in CLASSES:
            shutil.rmtree(documents / class_name, ignore_errors=True)
        for generated_file in (documents / "document_manifest.csv",):
            generated_file.unlink(missing_ok=True)
    documents.mkdir(parents=True, exist_ok=True)
    manifest: list[dict[str, str]] = []
    for class_no, class_name in enumerate(CLASSES):
        for index in range(ROWS_PER_CLASS):
            rng = random.Random(SEED + class_no * 100 + index)
            filename = f"{class_name}_{index + 1:02d}.pdf"
            relative_path = Path(class_name) / filename
            metadata = PDF_BUILDERS[class_name](documents / relative_path, index, rng)
            manifest.append(
                {
                    "file_path": relative_path.as_posix(),
                    "document_id": metadata["document_id"],
                    "expected_class": class_name,
                    "document_subtype": metadata["document_subtype"],
                    "page_count": "2",
                    "language": "en",
                }
            )
    with (documents / "document_manifest.csv").open(
        "w", newline="", encoding="utf-8"
    ) as handle:
        writer = csv.DictWriter(
            handle, fieldnames=tuple(manifest[0]), lineterminator="\n"
        )
        writer.writeheader()
        writer.writerows(manifest)


def generate_findings() -> list[dict[str, Any]]:
    rng = random.Random(SEED + 50_000)
    catalog = build_cve_catalog()
    cve_ids = list(catalog)
    # Weight the documented CVEs high so they always appear in the findings (the
    # gold document-enrichment join must be non-empty), and give the rest a long
    # tail. Documented CVEs get weight 40; others a smaller deterministic weight.
    cve_weighted = [
        (cve_id, 40 if catalog[cve_id]["documented"] else 3 + (i % 5))
        for i, cve_id in enumerate(cve_ids)
    ]
    asset_weighted = [(asset, asset[-1]) for asset in ASSETS]
    rows: list[dict[str, Any]] = []
    start = date(2025, 10, 1)
    scan_counter: dict[tuple[str, str], str] = {}
    for i in range(ROW_COUNT):
        asset = weighted_choice(rng, asset_weighted)
        cve_id = weighted_choice(rng, cve_weighted)
        cve = catalog[cve_id]
        day_offset = int(rng.triangular(0, 350, 250))
        scan_date = start + timedelta(days=day_offset)

        # One scan run groups many findings for an asset on a date; reuse the
        # same scan_id for the same (asset, date) so scan_count is meaningful.
        scan_key = (asset[0], scan_date.isoformat())
        if scan_key not in scan_counter:
            scan_counter[scan_key] = f"SCN-{scan_date.strftime('%Y%m%d')}-{len(scan_counter) + 1:04d}"
        scan_id = scan_counter[scan_key]

        cvss = cve["cvss_score"]
        severity = cve["severity"]
        category = cve["category"]

        # Status mix. Production during a Q1-2026 remediation backlog skews Open —
        # a traceable "production critical backlog" story for later exercises.
        in_backlog = asset[3] == "Production" and date(2026, 1, 15) <= scan_date <= date(2026, 3, 31)
        if in_backlog:
            status = rng.choices(
                ["Open", "In Remediation", "Resolved", "Accepted Risk"],
                weights=[58, 26, 12, 4], k=1,
            )[0]
        else:
            status = rng.choices(
                ["Open", "In Remediation", "Resolved", "Accepted Risk"],
                weights=[34, 24, 36, 6], k=1,
            )[0]

        age_days = int(rng.triangular(0, 210, 40))
        first_detected = scan_date - timedelta(days=age_days)

        base_hours = CATEGORY_BASE_HOURS[category]
        severity_factor = {
            "Critical": Decimal("1.6"),
            "High": Decimal("1.3"),
            "Medium": Decimal("1.0"),
            "Low": Decimal("0.7"),
        }[severity]
        jitter = Decimal(str(rng.choice([0.9, 0.95, 1.0, 1.05, 1.1])))
        remediation_hours = (base_hours * severity_factor * jitter).quantize(MONEY)

        weight = Decimal(asset[-1])
        weighted_risk = (cvss * weight).quantize(MONEY)
        asset_value_at_risk = (
            asset[7] * (cvss / Decimal(10)) * Decimal(str(rng.choice([0.85, 0.9, 1.0, 1.1])))
        ).quantize(MONEY, rounding=ROUND_HALF_UP)

        detected = datetime.combine(
            scan_date, datetime.min.time(), tzinfo=timezone.utc
        ) + timedelta(hours=6, minutes=i % 53)
        updated = detected + timedelta(days=rng.choice([0, 0, 1, 2]), hours=2)

        row = {
            "finding_id": f"FND-{i + 1:06d}",
            "scan_id": scan_id,
            "scan_date": scan_date,
            "detected_timestamp": detected,
            "asset_id": asset[0],
            "asset_name": asset[1],
            "asset_type": asset[2],
            "environment": asset[3],
            "business_unit": asset[4],
            "owner_team": asset[5],
            "cve_id": cve_id,
            "vulnerability_title": cve["title"],
            "vulnerability_category": category,
            "severity": severity,
            "cvss_score": cvss,
            "cvss_vector": cve["cvss_vector"],
            "status": status,
            "first_detected_date": first_detected,
            "age_days": age_days,
            "remediation_hours": remediation_hours,
            "asset_value_at_risk": asset_value_at_risk,
            "weighted_risk": weighted_risk,
            "remediation_sla_days": _sla_for(severity),
            "exploit_available": bool(cve["exploit_available"]),
            "detection_source": rng.choices(
                list(SCANNERS) + ["Manual Pentest"],
                weights=[26, 22, 20, 14, 12, 6], k=1,
            )[0],
            "source_updated_at": updated,
        }
        rows.append(row)
    return rows


def csv_value(value: Any) -> Any:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (date, datetime)):
        return value.isoformat()
    if isinstance(value, Decimal):
        return format(value, "f")
    return value


def write_lakebase_seed(rows: list[dict[str, Any]], transactional: Path) -> None:
    lakebase = transactional / "lakebase"
    shutil.rmtree(lakebase, ignore_errors=True)
    lakebase.mkdir(parents=True)
    with (lakebase / "scan_findings.csv").open(
        "w", newline="", encoding="utf-8"
    ) as handle:
        writer = csv.DictWriter(handle, fieldnames=TXN_FIELDS, lineterminator="\n")
        writer.writeheader()
        writer.writerows(
            {key: csv_value(row[key]) for key in TXN_FIELDS} for row in rows
        )
    columns = """
    finding_id varchar(20) PRIMARY KEY,
    scan_id varchar(40) NOT NULL,
    scan_date date NOT NULL,
    detected_timestamp timestamptz NOT NULL,
    asset_id varchar(20) NOT NULL,
    asset_name varchar(80) NOT NULL,
    asset_type varchar(40) NOT NULL,
    environment varchar(30) NOT NULL,
    business_unit varchar(60) NOT NULL,
    owner_team varchar(60) NOT NULL,
    cve_id varchar(24) NOT NULL,
    vulnerability_title varchar(200) NOT NULL,
    vulnerability_category varchar(60) NOT NULL,
    severity varchar(12) NOT NULL,
    cvss_score numeric(3,1) NOT NULL CHECK (cvss_score BETWEEN 0 AND 10),
    cvss_vector varchar(60) NOT NULL,
    status varchar(20) NOT NULL,
    first_detected_date date NOT NULL,
    age_days integer NOT NULL CHECK (age_days >= 0),
    remediation_hours numeric(8,2) NOT NULL CHECK (remediation_hours >= 0),
    asset_value_at_risk numeric(14,2) NOT NULL CHECK (asset_value_at_risk >= 0),
    weighted_risk numeric(10,2) NOT NULL CHECK (weighted_risk >= 0),
    remediation_sla_days integer NOT NULL CHECK (remediation_sla_days > 0),
    exploit_available boolean NOT NULL,
    detection_source varchar(40) NOT NULL,
    source_updated_at timestamptz NOT NULL
""".strip()
    schema_sql = f"""-- Synthetic Lakebase/PostgreSQL source schema. Safe to rerun.
CREATE SCHEMA IF NOT EXISTS security_seed;

CREATE TABLE IF NOT EXISTS security_seed.scan_findings (
{columns}
);

CREATE INDEX IF NOT EXISTS scan_findings_scan_date_idx
    ON security_seed.scan_findings (scan_date);
CREATE INDEX IF NOT EXISTS scan_findings_cve_idx
    ON security_seed.scan_findings (cve_id, severity);
CREATE INDEX IF NOT EXISTS scan_findings_source_updated_idx
    ON security_seed.scan_findings (source_updated_at);

-- Required by Lakebase Lakehouse Sync / CDF so updates and deletes carry the
-- complete row image into the Unity Catalog history table.
ALTER TABLE security_seed.scan_findings REPLICA IDENTITY FULL;
"""
    (lakebase / "schema.sql").write_text(schema_sql, encoding="utf-8", newline="\n")
    copy_columns = ", ".join(TXN_FIELDS)
    load_sql = f"""\\set ON_ERROR_STOP on
BEGIN;
TRUNCATE TABLE security_seed.scan_findings;
\\copy security_seed.scan_findings ({copy_columns}) FROM 'data/security/transactional/lakebase/scan_findings.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');
COMMIT;
"""
    (lakebase / "load.sql").write_text(load_sql, encoding="utf-8", newline="\n")


def arrow_schema() -> pa.Schema:
    return pa.schema(
        [
            pa.field("finding_id", pa.string()),
            pa.field("scan_id", pa.string()),
            pa.field("scan_date", pa.date32()),
            pa.field("detected_timestamp", pa.timestamp("us", tz="UTC")),
            pa.field("asset_id", pa.string()),
            pa.field("asset_name", pa.string()),
            pa.field("asset_type", pa.string()),
            pa.field("environment", pa.string()),
            pa.field("business_unit", pa.string()),
            pa.field("owner_team", pa.string()),
            pa.field("cve_id", pa.string()),
            pa.field("vulnerability_title", pa.string()),
            pa.field("vulnerability_category", pa.string()),
            pa.field("severity", pa.string()),
            pa.field("cvss_score", pa.decimal128(3, 1)),
            pa.field("cvss_vector", pa.string()),
            pa.field("status", pa.string()),
            pa.field("first_detected_date", pa.date32()),
            pa.field("age_days", pa.int32()),
            pa.field("remediation_hours", pa.decimal128(8, 2)),
            pa.field("asset_value_at_risk", pa.decimal128(14, 2)),
            pa.field("weighted_risk", pa.decimal128(10, 2)),
            pa.field("remediation_sla_days", pa.int32()),
            pa.field("exploit_available", pa.bool_()),
            pa.field("detection_source", pa.string()),
            pa.field("source_updated_at", pa.timestamp("us", tz="UTC")),
        ]
    )


def normalize_delta(delta_path: Path) -> None:
    """Remove writer UUIDs/timestamps without changing the valid Delta snapshot."""
    log_path = delta_path / "_delta_log" / "00000000000000000000.json"
    actions = [
        json.loads(line) for line in log_path.read_text(encoding="utf-8").splitlines()
    ]
    add_actions = [action["add"] for action in actions if "add" in action]
    old_paths = sorted(add["path"] for add in add_actions)
    replacements: dict[str, str] = {}
    for index, old_path in enumerate(old_paths):
        new_path = f"part-{index:05d}-security-scan.c000.snappy.parquet"
        (delta_path / old_path).rename(delta_path / new_path)
        replacements[old_path] = new_path
    for action in actions:
        if "commitInfo" in action:
            action["commitInfo"]["timestamp"] = GENERATED_AT_MS
            action["commitInfo"].get("operationMetrics", {})["execution_time_ms"] = 0
        if "metaData" in action:
            action["metaData"]["id"] = "09232026-0000-4000-8000-000000000013"
            action["metaData"]["createdTime"] = GENERATED_AT_MS
        if "add" in action:
            action["add"]["path"] = replacements[action["add"]["path"]]
            action["add"]["modificationTime"] = GENERATED_AT_MS
            action["add"]["stats"] = json.dumps(
                json.loads(action["add"]["stats"]),
                separators=(",", ":"),
                sort_keys=True,
            )
    normalized = "".join(
        json.dumps(action, separators=(",", ":"), sort_keys=True) + "\n"
        for action in actions
    )
    log_path.write_text(normalized, encoding="utf-8", newline="\n")


def write_delta_seed(rows: list[dict[str, Any]], transactional: Path) -> None:
    delta_path = transactional / "delta" / "scan_findings"
    shutil.rmtree(delta_path.parent, ignore_errors=True)
    delta_path.parent.mkdir(parents=True)
    table = pa.Table.from_pylist(rows, schema=arrow_schema())
    write_deltalake(
        delta_path,
        table,
        mode="error",
        name="security_scan_findings_seed",
        description="Deterministic synthetic infrastructure-security scan-findings fallback seed",
        configuration={"delta.enableChangeDataFeed": "true"},
    )
    normalize_delta(delta_path)


def artifact_files(output_root: Path) -> list[Path]:
    documents = output_root / "documents"
    transactional = output_root / "transactional"
    files = list(documents.glob("*/*.pdf")) + [documents / "document_manifest.csv"]
    files += [
        path
        for path in transactional.rglob("*")
        if path.is_file() and path.name != "checksums.sha256"
    ]
    return sorted(files, key=lambda path: path.relative_to(output_root).as_posix())


def file_hashes(output_root: Path) -> dict[str, str]:
    return {
        path.relative_to(output_root).as_posix(): hashlib.sha256(
            path.read_bytes()
        ).hexdigest()
        for path in artifact_files(output_root)
    }


def write_checksums(output_root: Path) -> None:
    checksum_file = output_root / "transactional" / "checksums.sha256"
    hashes = file_hashes(output_root)
    checksum_file.write_text(
        "".join(f"{digest}  {path}\n" for path, digest in hashes.items()),
        encoding="utf-8",
        newline="\n",
    )


def generate(output_root: Path) -> None:
    output_root.mkdir(parents=True, exist_ok=True)
    generate_pdfs(output_root)
    rows = generate_findings()
    transactional = output_root / "transactional"
    transactional.mkdir(parents=True, exist_ok=True)
    write_lakebase_seed(rows, transactional)
    write_delta_seed(rows, transactional)
    write_checksums(output_root)


def load_csv_rows(
    path: Path, expected_fields: tuple[str, ...] | None = None
) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        if (
            expected_fields is not None
            and tuple(reader.fieldnames or ()) != expected_fields
        ):
            raise AssertionError(
                f"unexpected CSV schema in {path}: {reader.fieldnames}"
            )
        return list(reader)


def validate(output_root: Path) -> dict[str, Any]:
    documents = output_root / "documents"
    manifest_rows = load_csv_rows(documents / "document_manifest.csv")
    class_counts: Counter[str] = Counter()
    for row in manifest_rows:
        pdf_path = documents / row["file_path"]
        if not pdf_path.is_file():
            raise AssertionError(f"missing PDF: {pdf_path}")
        reader = PdfReader(pdf_path)
        text = "\n".join(page.extract_text() or "" for page in reader.pages)
        if len(reader.pages) != 2 or len(text) < 900:
            raise AssertionError(
                f"PDF is not a substantial two-page document: {pdf_path}"
            )
        class_counts[row["expected_class"]] += 1
    expected_counts = Counter({class_name: ROWS_PER_CLASS for class_name in CLASSES})
    if (
        class_counts != expected_counts
        or len(manifest_rows) != len(CLASSES) * ROWS_PER_CLASS
    ):
        raise AssertionError(f"unexpected PDF distribution: {class_counts}")

    # Each cve_advisory PDF must publish exactly one of the five documented CVE
    # ids (the document join key that silver_cve_advisory.cve_id will carry).
    advisory_ids = {
        row["document_id"]
        for row in manifest_rows
        if row["expected_class"] == "cve_advisory"
    }
    documented_ids = {cve[0] for cve in DOCUMENTED_CVES}
    if advisory_ids != documented_ids:
        raise AssertionError(
            f"cve_advisory document ids {advisory_ids} do not match the "
            f"documented CVE set {documented_ids}"
        )

    catalog = build_cve_catalog()
    valid_assets = {asset[0] for asset in ASSETS}
    csv_path = output_root / "transactional" / "lakebase" / "scan_findings.csv"
    csv_rows = load_csv_rows(csv_path, TXN_FIELDS)
    if len(csv_rows) != ROW_COUNT:
        raise AssertionError(f"expected {ROW_COUNT} finding rows, found {len(csv_rows)}")
    if len({row["finding_id"] for row in csv_rows}) != ROW_COUNT:
        raise AssertionError("finding IDs are not unique")
    observed_cves: set[str] = set()
    for row in csv_rows:
        cve = catalog.get(row["cve_id"])
        if cve is None or row["asset_id"] not in valid_assets:
            raise AssertionError(
                f"invalid dimension reference in {row['finding_id']}"
            )
        observed_cves.add(row["cve_id"])
        cvss = Decimal(row["cvss_score"])
        if str(cvss) != str(cve["cvss_score"]) or row["severity"] != cve["severity"]:
            raise AssertionError(
                f"CVE attributes not consistent for {row['finding_id']}"
            )
        if _severity_for(cvss) != row["severity"]:
            raise AssertionError(
                f"severity does not match CVSS band in {row['finding_id']}"
            )
        # weighted_risk = cvss * asset criticality weight (exact, quantized).
        # Re-derive the weight from the asset id to keep the invariant checkable.
        weight = Decimal(next(a[-1] for a in ASSETS if a[0] == row["asset_id"]))
        if (cvss * weight).quantize(MONEY) != Decimal(row["weighted_risk"]):
            raise AssertionError(
                f"weighted_risk arithmetic is incoherent in {row['finding_id']}"
            )
        # first_detected_date + age_days == scan_date.
        first = date.fromisoformat(row["first_detected_date"])
        if first + timedelta(days=int(row["age_days"])) != date.fromisoformat(
            row["scan_date"]
        ):
            raise AssertionError(
                f"age_days/first_detected_date incoherent in {row['finding_id']}"
            )
        if row["exploit_available"] not in ("true", "false"):
            raise AssertionError(
                f"exploit_available is not a boolean literal in {row['finding_id']}"
            )
    # The document-enrichment join must be non-empty: every documented CVE must
    # appear in the findings so gold document enrichment is exercised.
    missing_documented = documented_ids - observed_cves
    if missing_documented:
        raise AssertionError(
            f"documented CVEs absent from findings (gold join would be empty): "
            f"{sorted(missing_documented)}"
        )

    delta_path = output_root / "transactional" / "delta" / "scan_findings"
    delta = DeltaTable(delta_path)
    delta_table = delta.to_pyarrow_table()
    if delta_table.num_rows != ROW_COUNT or delta.version() != 0:
        raise AssertionError("Delta seed is not a readable 3,000-row version-0 table")
    if tuple(delta_table.column_names) != TXN_FIELDS:
        raise AssertionError(f"unexpected Delta schema: {delta_table.column_names}")
    delta_total = sum(
        delta_table.column("asset_value_at_risk").to_pylist(), Decimal("0.00")
    )
    csv_total = sum(
        (Decimal(row["asset_value_at_risk"]) for row in csv_rows), Decimal("0.00")
    )
    if delta_total != csv_total:
        raise AssertionError(
            "Delta and Lakebase seeds do not contain the same value at risk"
        )

    schema_path = output_root / "transactional" / "lakebase" / "schema.sql"
    parsed = sqlglot.parse(schema_path.read_text(encoding="utf-8"), read="postgres")
    if len(parsed) != 6:
        raise AssertionError(
            f"expected six PostgreSQL DDL statements, parsed {len(parsed)}"
        )
    if "REPLICA IDENTITY FULL" not in schema_path.read_text(encoding="utf-8"):
        raise AssertionError("Lakebase CDF source must use REPLICA IDENTITY FULL")
    load_sql = (output_root / "transactional" / "lakebase" / "load.sql").read_text(
        encoding="utf-8"
    )
    copy_match = re.search(
        r"\\copy\s+security_seed\.scan_findings\s*\((.*?)\)\s+FROM",
        load_sql,
        re.IGNORECASE,
    )
    if copy_match is None:
        raise AssertionError(
            "Lakebase load.sql does not contain the expected psql copy command"
        )
    copy_columns = tuple(column.strip() for column in copy_match.group(1).split(","))
    if copy_columns != TXN_FIELDS:
        raise AssertionError("Lakebase copy column order does not match the seed CSV")

    expected_hashes: dict[str, str] = {}
    checksum_path = output_root / "transactional" / "checksums.sha256"
    for line in checksum_path.read_text(encoding="utf-8").splitlines():
        digest, relative = line.split("  ", 1)
        expected_hashes[relative] = digest
    actual_hashes = file_hashes(output_root)
    if expected_hashes != actual_hashes:
        raise AssertionError(
            "artifact checksum manifest does not match generated files"
        )
    return {
        "seed": SEED,
        "pdf_total": sum(class_counts.values()),
        "pdf_by_class": dict(sorted(class_counts.items())),
        "finding_rows": len(csv_rows),
        "distinct_cves": len(observed_cves),
        "documented_cves": len(documented_ids),
        "delta_version": delta.version(),
        "delta_value_at_risk": format(delta_total, ".2f"),
        "postgres_ddl_statements": len(parsed),
        "artifact_count": len(actual_hashes),
    }


def check_reproducible() -> dict[str, Any]:
    with (
        tempfile.TemporaryDirectory(prefix="security-seed-a-") as first_dir,
        tempfile.TemporaryDirectory(prefix="security-seed-b-") as second_dir,
    ):
        first = Path(first_dir) / "security"
        second = Path(second_dir) / "security"
        generate(first)
        generate(second)
        first_result = validate(first)
        validate(second)
        first_hashes = file_hashes(first)
        second_hashes = file_hashes(second)
        if first_hashes != second_hashes:
            differences = sorted(
                set(first_hashes) ^ set(second_hashes)
                | {
                    path
                    for path in first_hashes.keys() & second_hashes.keys()
                    if first_hashes[path] != second_hashes[path]
                }
            )
            raise AssertionError(
                f"same-seed generation is not byte-identical: {differences}"
            )
        first_result["reproducible_files_compared"] = len(first_hashes)
        first_result["byte_identical"] = True
        return first_result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data/security"),
        help="Security output root (default: data/security)",
    )
    parser.add_argument(
        "--validate-only",
        action="store_true",
        help="Validate existing outputs without regenerating",
    )
    parser.add_argument(
        "--check-reproducible",
        action="store_true",
        help="Generate twice in temporary directories and compare every byte",
    )
    args = parser.parse_args()
    if args.check_reproducible:
        result = check_reproducible()
    else:
        if not args.validate_only:
            generate(args.output)
        result = validate(args.output)
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
